### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by flyingOwl** [paroj/DSub2000#21]
There should be an updated readme. The current one is not very useful, to put it nicely.

The new readme should include:

- Some introductory sentences with a short statement, that this is a fork of DSub
- A list of features
- A few nice screenshots
- once we have them: links to release page and app stores

**Comment by paroj** [comment]
- added some text in 273eeffbc713c7bc0457b061b93a3d2b686345f3
- put the fork info in "About" (top right)
- for the screenshots: we could use them as a manual, highlighting some UI elements

regarding the last point, it took me a while to figure out that:
- the playlist and the now playing tab are different things, where the latter can be reordered on the fly
- you can tap on the "downloaded" icon to view the song details (thats rather a UI bug though)
- the difference between cache and permanent cache still eludes me

**Comment by norohind** [comment]
Regarding screenshots, we going to need include them for fdroid publishing. Could as well resuse for README.

**Comment by norohind** [comment]
> put the fork info in "About" (top right)

Given description in daneren2005's repo is *Home of the DSub Android client fork* I wonder if it's also a fork and thus DSub2000 is a fork of a fork.

> the difference between cache and permanent cache still eludes me

I believe it's all about permanently cached songs won't get deleted in attempt to maintain user set cache size.

Regarding unknown features, maybe somebody can shed light to ones from dsub's fdroid description:
>  * Lockscreen controls (ICS+)
>  * Gapless Playback (JB+)

What is `ICS+` and `JB+`?

**Comment by paroj** [comment]
>  I wonder if it's also a fork and thus DSub2000 is a fork of a fork.

technically, yes. However I guess its enough to convey that this is a DSub fork. Someone could write down the history of this, starting from the original Subsonic Android client and also include the bits that come from vanilla:
https://github.com/vanilla-music/vanilla/tree/master/app/src/main/java/ch/blinkenlights/bastp

but that is an exercise for later.. ;)

> I believe it's all about permanently cached songs won't get deleted in attempt to maintain user set cache size.

we will have to check the code I guess ^^

> What is ICS+ and JB+?

those are Android API levels, see:
https://en.wikipedia.org/wiki/Android_version_history

**Comment by paroj** [comment]
fixed with 79f904b5a1ecef1c68a6479cfc7f9a7a9053eee5
