### ISSUE TITLE
Is this fork dead as well?

### ISSUE THREAD

**Issue by fault1er1** [paroj/DSub2000#26]
Hi!

I just wanted to know if this fork will get updates in the future or if it's already not maintained anymore?

I'm using kagemomijis fork of the airsonic server and everything works just fine, but there's no actively maintained android app :(

**Comment by norohind** [comment]
Hi. It's complicated. I would say it just gets updated very rare.

Personally I am still using dsub2000 daily, I'm still suffering from some problems, eventually, I will find time to deal with it and contribute patches. I don't know when I will do it, but I am pretty confident it will happen at some point.

**Comment by fault1er1** [comment]
Ah, okay. Thank you for your kind answer. I literally just have to wait, because I can't code my own sw. To be honest, I even have no idea how to build an apk file on my own from this repository, everytime i try to build it in android studio it throws a bunch of errors and I'm unaware to debug :(
Btw: Which version of the Subsonic streaming server do you use on daily basis?

**Comment by norohind** [comment]
It's navidrome. I first have read about it on HN. Almost immiditaly tried and neve really looked back on the alternatives. Though now would also tried out gonic, seems to be cool.
