### ISSUE TITLE
CI artifacts expired

### ISSUE THREAD

**Issue by sentriz** [paroj/DSub2000#27]
hi all, seems like the retention of the CI logs and artifacts is somewhere around 3 months since the APK is not available anymore

could we re-run the job please to product a new artifact? thanks!

https://github.com/paroj/DSub2000/actions/runs/9341688641

**Comment by norohind** [comment]
Hmm. I think we should establish a proper release then. Releases artifacts shouldn't expire.

**Comment by paroj** [comment]
the proper release would be via fdroid. we should not encourage people to download apks off github. I hope I can do the push for fdroid next week. I have some time then.

closing this as the CI is creating another artifact right now
