### ISSUE TITLE
Question: How will you distribute this?

### ISSUE THREAD

**Issue by khers** [paroj/DSub2000#5]
Do you plan to publish on Google Play, fDroid, Amazon App store?

I'd really like to see it show up in places where it is easier to install (for instance I have a device that can only use the Play store and side loading is prohibited). Thanks for picking this up!

**Comment by paroj** [comment]
first step is probably building an apk with github actions, then I would go for fdroid as I already got an app there.
I dont have a google play developer account, but further down the road it would be an option..

Either way, if we start distributing this, then further re-branding is needed first - beyond just changing the repo name

**Comment by norohind** [comment]
If we're going to rebrand the fork, then it would be appropriate to somehow separate those changes from what currently is present in PR to upstream (https://github.com/daneren2005/Subsonic/pull/1126). May be set that PR against some designated for it branch? Else it gonna be not much *conservative* towards upstream :)

**Comment by norohind** [comment]
Regarding publication in Fdroid: the application requires libraries from third party maven repo http://4thline.org/m2. Third party maven repositories is against Fdroid inclusion policy and the maintainers  made it clear to get rid of 4thline repo (https://gitlab.com/fdroid/fdroiddata/-/merge_requests/3501). The required libs (cling and cling-support) aren't on maven central. There is a supported fork of cling - jupnp (https://github.com/jupnp/jupnp) but I failed to build the app with fresh versions of fork and old versions are not available on maven central. So, that's the problem to solve.

**Comment by norohind** [comment]
In order to avoid duplicated work: I'm working on rebranding the fork and later intending to maintain process of submitting the app to fdroid

**Comment by norohind** [comment]
I paused my work on publishing it in fdroid due to lack of free time. I would be glad if somebody will pick it up, otherwise, eventually, I will get it done myself. 

Here's my draft of metadata file for fdroid:
```
Categories:
  - Multimedia
License: GPL-3.0-only
SourceCode: https://github.com/paroj/DSub2000
IssueTracker: https://github.com/paroj/DSub2000/issues
Changelog: https://github.com/paroj/DSub2000/releases

AutoName: DSub2000
Description: |-
  Connect to your Subsonic-comptible server and listen to your music wherever you go. Songs
  are cached for playback to save on your mobile bandwidth and to make them
  available when you have no connection at all.

  * Lockscreen controls (ICS+)
  * Gapless Playback (JB+)
  * Notification prev/pause/next buttons
  * Quick add/remove songs to playlist
  * Pause playback when other apps request audio focus (navigation, etc)
  * Option to gather logs and send them via email for newer versions of Android
  * Drag and drop songs to rearrange your playlist on the Now Playing tab
  * User defined Cache Size, Network Timeout, and Buffer Length

  Subsonic is a cross-platform FOSS media server that's capable of indexing very
  large media collections. The server can transcode if necessary so that the app
  can play files that your device may not normally support.

  The app is set up to access a demo server on the internet for trying it out. In
  order to use this app with your own Subsonic server beyond a trial period, a key
  must be obtained by making a donation. (A key isn't required to use the
  <a href="https://github.com/Mach5/supersonic">Supersonic</a> variant.)

  Recent versions of this app depend on the non-free Google Play Services library.

RepoType: git
Repo: https://github.com/paroj/DSub2000

Builds:
  - versionName: 5.5.3
    versionCode: 208
    commit: 00516356182c7320e54a009f7155ae3c1de5f66c
    subdir: app
    gradle:
      - floss

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 5.5.3
CurrentVersionCode: 208
```

Before release, make sure to update in-app changelog (accessible via main screen -> three dots -> changelog), it's located in file app/src/main/res/xml/changelog.xml, example of required changes can be seen in this commit https://github.com/daneren2005/Subsonic/commit/47cd98ef2b6c9cbe17b64da67221f3238818a384.

I also wonder if fdroid metadata directory with screenshots and everything should be a submodule so we won't make heavier main repo by including/eventually updating screenshots.

**Comment by paroj** [comment]
> Before release, make sure to update in-app changelog

already done in 9d2026e52dc9a1d52a83bc758f270157de733dd6 :D

**Comment by paroj** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15936

**Comment by dessalines** [comment]
This still isn't on f-droid, izzyondroid, or the google play store. People can't use it if it's not obtainable.

**Comment by Jasper-Ben** [comment]
> This still isn't on f-droid, izzyondroid, or the google play store. People can't use it if it's not obtainable.

The merge request for including the app in fdroid has been merged. But it takes up to 7 days to show up in the store, see link in said MR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15936#note_2153840167

So you'll have to be patient or get it using other means, e.g. with obtainium.

**Comment by dessalines** [comment]
I'd also request for it to be added to izzyondroid. It pulls from your own github releases daily. I also release several apps, and its the best method for people to get anything you want to release.

**Comment by paroj** [comment]
app is now on fdroid
